### ISSUE TITLE
darkcoin or dash public and private prefix?

### ISSUE THREAD

**Issue by pokerplatform** [Dwerg/walletaid#2]
Hi i dont know the prefix for darkcoin aka dash public and private prefix for using the recovery tool?

can you help me please, ive been looking everywhere and i failed it starts with X the address.

thanks

**Comment by Dwerg** [comment]
You can find the information you need on the github of whatever coin you need it for. You'll find it in src/chainparams.cpp, then you'll need to find "base58Prefixes[PUBKEY_ADDRESS]" and "base58Prefixes[SECRET_KEY]". It will show the prefix for public and private key respectively. It may be in decimal in which case it must be converted to hexadecimal first, there's plenty of calculators online that will do this easily.

For darkcoin the pubkeyprefix appears to be "8B" and the privkeyprefix "EF".

Sorry for very late response, I'm not really active.
